name: Bug report
description: Create a report to help us improve
labels:
  - bug
body:
  - id: project
    type: dropdown
    attributes:
      label: Project
      description: Select a project the bug belongs to.
      options:
        - core
        - monad
        - uri
    validations:
      required: true
  - id: description
    type: textarea
    attributes:
      label: Description
      description: Describe the bug. Code sample or link to the repo would help a lot.
    validations:
      required: true
  - id: expected
    type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - id: keywords
    type: input
    attributes:
      label: Keywords
      description: Include keywords that might help others with the same question find this issue
