name: Feature request
description: Suggest an idea for the project
labels:
  - enhancement
body:
  - id: project
    type: dropdown
    attributes:
      label: Project
      description: Select a project the requested feature belongs to.
      options:
        - core
        - monad
        - uri
  - id: problem
    type: textarea
    attributes:
      label: Problem
      description: Describe the problem the requested feature should solve.
    validations:
      required: true
  - id: solution
    type: textarea
    attributes:
      label: Solution
      description: Describe the expected/possible solution of the problem. Code samples are highly appeciated.
    validations:
      required: true
  - id: keywords
    type: input
    attributes:
      label: Keywords
      description: Include keywords that might help others with the same question find this issue
