name: Feature request
description: Suggest an idea for the project
title: '[Request]'
labels:
  - enhancement
body:
  - id: project
    type: dropdown
    attributes:
      label: Project
      description: Select a project
      multiple: false
      options:
        - core
        - monad
        - uri
    validations:
      required: true
  - id: problem
    type: textarea
    attributes:
      label: Problem
      description: A clear and concise description of the problem
    validations:
      required: true
  - id: solution
    type: textarea
    attributes:
      label: Solution
      description: A clear and concise description of the solution
    validations:
      required: true
  - id: keywords
    type: input
    attributes:
      label: Search keywords
      description: A list of keywords to help find this issue
    validations:
      required: false
